### ISSUE TITLE
VSR / Texte à trou - présentation des solutions

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-quizs#45]
A voir si les solutions et leurres définis pour chaque trou sont présentées à chaque trou ou bien sur le trou sur lequel elles ont été saisies.
Dans l'exemple ci-dessous elles sont regroupées dans une même liste présentée pour chaque trou de la même façon
Texte, solutions et leurres saisis
![texte a trou complet](https://cloud.githubusercontent.com/assets/20283655/24808308/7c287bfc-1bbb-11e7-80d6-5c9093713a66.PNG)

Présentation des solutions en mode aperçu
![texte a trou liste de toutes les solutions par trou](https://cloud.githubusercontent.com/assets/20283655/24808320/86519910-1bbb-11e7-8f0e-516bc95fa7c6.PNG)

![texte a trou liste de toutes les solutions 2e trou](https://cloud.githubusercontent.com/assets/20283655/24808438/fb68442e-1bbb-11e7-8fa3-b29ff1c05d65.PNG)

**Comment by TestsCGI** [comment]
https://github.com/laclasse-com/service-quizs/issues/45

**Comment by skhirimohamed** [comment]
les solutions et leurres définis pour chaque trou sont présentées à chaque trou .
