### ISSUE TITLE
VSR / Texte à trou : rédaction du texte - impossible d'avoir 2 trous consécutifs

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-quizs#46]
Il n'est pas possible d'avoir un texte avec 2 trous consécutifs. En laissant un espace de texte vierge et en renseignant les solutions et leurres, ces données ne sont pas prises en compte lors de l'enregistrement.
![texte avec 2 trous consecutifs](https://cloud.githubusercontent.com/assets/20283655/24808818/a17b1002-1bbd-11e7-9c78-e54a8d0f6ee5.PNG)

Après enregistrement
![resultat apres enregistrement](https://cloud.githubusercontent.com/assets/20283655/24808824/a7707dc6-1bbd-11e7-915a-4590330091aa.PNG)

**Comment by TestsCGI** [comment]
Le texte à trous doit se terminer par un champ texte sinon la dernière solution n'est pas présentée.

**Comment by skhirimohamed** [comment]
afin de placer deux trous consécutifs l'utilisateur devra mettre ## dans le champs associé.
