### ISSUE TITLE
VSR/ Lecture quiz : bouton démarrer ko

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-quizs#48]
Lecture par un enseignant d'un des quiz qu'il a créé : le bouton démarrer le quiz ne fonctionne pas

**Comment by TestsCGI** [comment]
Le bouton Démarrer est activé une fois que le quiz a été publié

**Comment by TestsCGI** [comment]
Même chose pour un quiz de la Bibliothèque : il ne peut être lu à moins d'être publié

**Comment by skhirimohamed** [comment]
corrigé

**Comment by TestsCGI** [comment]
ok
