### ISSUE TITLE
Recette Quiz

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-quizs#5]
### Ergonomie générale
- [ ] Emplacement des boutons d'actions et d'annulation (annuler est parfois à droite, parfois à gauche

### Liste
- [ ] Confirmation sur suppression d'un quiz
- [ ] Fonction de duplication : Lorsqu'on duplique un quiz publié, on a les même infos de publication sur le quiz publié, mais en apparence seulement car lorqu'on rafraichit la page, le nouveau quiz n'est en fait pas publié.

### Création
- [ ] Création de quizs vides
- [ ] sur création question : A la validation, rien n'indique que la question doit être renseignée

#### Questions par défaut dans le champ "Question"
- [ ] Pour les QCM : Question par défaut "Cochez la ou les bonnes réponses."
- [ ] Pour les Textes à trous, Question par défaut "Remplissez les trous avec propositions qui vous semblent justes."
- [ ] Pour les associations, Question par défaut  "Associez les propositions entre elles"

### Execution
- [ ] Confirmation sur bouton "quitter" lorsqu'on joue un quiz
- [ ] "Mélanger les réponses" dans QCM n'est pas pris en compte lorsqu'on le change de valeur et qu'on valide

### Publication
- [ ] Mettre la date du jour par défaut dans le champ "Du"
- [ ] Mettre la date du jour + 15 jours par défaut dans le champ "Au"

### Session
- [ ] trier la liste des sessions d'un même quiz d'un élève dans l'ordre chronologique (actuellement c'est trié par score, ce qui ne permet pas d’appréhender facilement la régresssion ou la progression de l'élève dans le temps)
- [ ] Coté prof : pour un quiz publié à plusieurs classes (mettons 6A et 6B) que l'on clique sur 6A ou 6B, la liste des sessions est la même et il faut refiltrer la liste des sessions après.
- [ ] Impossible de cliquer sur les sessions de la liste : ça devrait nous emmener vers le détail de la session.

### Liste des dernières sessions
- [ ] Qu'on clique sur l'une au l'autre des sessions récentes, on arrive toujours au tableau principal de la liste des sessions. La section "sessions récentes" doit afficher des lien donnant un accès direct à la session de l'élève.

**Comment by hquenin** [comment]
Petite Questions:

l'emplacement des boutons j'ai fait que suivre les maquettes, du coup gauche ou droite ?

tu ne veux pas que l'on puisse créer de quiz vide ?
je trouve cela pratique si on veut commencer à paramétrer et f

**Comment by Pilooz** [comment]
Je comprends ce que tu dis sur le quiz vide, mais dans ce cas, il faut forcer l'utilisateur à saisir un titre de quiz sinon on a des lignes vides dans la liste et ça fait plutôt "buggy" que "feature" :)

**Comment by hquenin** [comment]
je peux l’empêcher de faire retour s'il n'a pas mis le titre du quiz :)

Confirmation sur suppression d'un quiz ### Création: je ne comprends pas car j'ai déjà une confirm pour supprimer un quiz

**Comment by Pilooz** [comment]
Oui, en signalant qu'il faut mettre un titre : focus ou  Ouverture du Popup "titre" forcé.

**Comment by hquenin** [comment]
je lui ouvre la modal pour remplir le titre du quiz
ça le forcera !!

**Comment by Pilooz** [comment]
:+1:

**Comment by hquenin** [comment]
pour les valeurs par défaut, c'est un placeholder que tu veux ?

**Comment by Pilooz** [comment]
Non, une vrai valeur pour ne pas avoir à saisir ce champ si on veut aller vite

**Comment by hquenin** [comment]
ok d'accord

**Comment by Pilooz** [comment]
Si je suis prof, comment je vois toute la correction d'un quiz d'une session d'un élève ? (en fait comment j'ai accès à sa copie, son travail)

**Comment by hquenin** [comment]
Normalement tu cliques sur la session de l'élève

Par contre cela est fait exprès d'avoir rien mis dans les dates de publication par défaut, pour publier un quiz sans date d'expiration

**Comment by Pilooz** [comment]
Lorsqu'on clique sur les sessions d'élèves, il ne se passe rien.

**Comment by hquenin** [comment]
Ajoute le alors je corrigerais

**Comment by hquenin** [comment]
pour la duplication c'est normal que l'on ne duplique pas les publications car tous les utilisateurs non pas les mêmes classes par contre c'est pas normal que coté client elles soient dupliqué
