### ISSUE TITLE
VSR/ Pas de bouton pour fermer la fenêtre de publication

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-quizs#52]
Lorsqu'on publie un quiz la fenêtre utilisée pour définir la période de publication ne peut être fermée qu'avec la croix. Il n'y pas de bouton pour le faire.
![fermeture de la fenetre publication](https://cloud.githubusercontent.com/assets/20283655/24810935/68705860-1bc4-11e7-8ce9-8a2ad5f3a399.PNG)

**Comment by skhirimohamed** [comment]
il y a le petit X dans la barre bleue a droite, vous voulez que je remplace ça par un bouton ?

**Comment by TestsCGI** [comment]
Oui ajout de 2 boutons (pour avoir un fonctionnement similaire au reste de l'application) : Valider / Annuler
