### ISSUE TITLE
VSR/ Accès au détail d'une session

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-quizs#56]
Avec le compte enseignant efulchiron (mot de passe : efulchiron), le détail de la session de Guillaume Bruno pour le quiz exo 1 n'est pas correct.
![detail enseignant](https://cloud.githubusercontent.com/assets/20283655/24961015/c8de4640-1f97-11e7-91f7-be5040ca945e.PNG)

En se connectant avec le compte de l'élève gbruno (mdp : gbruno), le détail de cette même session est correct.
![detail eleve](https://cloud.githubusercontent.com/assets/20283655/24961029/d1ccda46-1f97-11e7-824f-b1123e8e1bea.PNG)

**Comment by TestsCGI** [comment]
Lorsqu'on quitte l'accès au détail d'une session, au lieu de revenir sur la page des résultats, on revient sur la page mes quiz

**Comment by skhirimohamed** [comment]
J'ai pas ce praJe n'ai pas ce probleme.
