### ISSUE TITLE
Visualisation des sessions

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-quizs#6]
Il y a un mélange de sessions.
J'ai publié un quiz dans 2 classes et fait faire le quiz par deux élève des deux classes.

![session-eleve](https://cloud.githubusercontent.com/assets/1265220/12974110/aa2f46c6-d0b1-11e5-9e0c-c4983766de13.png)

Toutes les sessions apparaîssent sous le même nom d'élève (écran prof)
A proiri la premiere session présentée dans l'écran ci-dessous appartient à l'élève ci-dessus !
![session-prof](https://cloud.githubusercontent.com/assets/1265220/12974113/ad47d346-d0b1-11e5-863f-40c6020973e8.png)

**Comment by hquenin** [comment]
peut tu me donner les comptes des élèves et du profs
