### ISSUE TITLE
VSR / Affichage des quiz pour le parent

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-quizs#61]
Le parent n'accède pas à la liste des quiz publiés à son enfant. Il ne peut consulter que les résultats des sessions effectuées par son enfant.
![liste quiz parent](https://cloud.githubusercontent.com/assets/20283655/24967657/24b69522-1fab-11e7-8daf-618cf4205575.PNG)

**Comment by skhirimohamed** [comment]
corrigé

**Comment by TestsCGI** [comment]
OK. Il a fallu rafraîchir la page pour lister les quiz correctement.
