### ISSUE TITLE
VSR / Gestion des sessions élèves pour un quiz n'étant plus publié

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-quizs#62]
L'élève continue d'avoir accès aux sessions réalisées sur des quiz n'étant plus publiés
Exemple ci-dessous : exo 1 / mon autre quiz

Vue enseignant des publications expirées
![enseignant publications expirees](https://cloud.githubusercontent.com/assets/20283655/24996721/36aba284-2034-11e7-9368-b829e8355779.PNG)

Vue élève mes résultats
![resultats eleve](https://cloud.githubusercontent.com/assets/20283655/24996746/5ec2a772-2034-11e7-836a-c444b6773729.PNG)

**Comment by skhirimohamed** [comment]
l'eleve peut voir les resultats de quiz qui les a fait meme si la periode de publication est expirées.

**Comment by TestsCGI** [comment]
Conforme au résultat attendu
